name: Conditional Actions

on: [push, pull_request]

env:
  image-push-owner: 'zeeke111'

jobs:

  conditional-job:
    
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: run
      if: ${{ github.repository_owner == env.image-push-owner }}
      run: echo "Hello World!"
